version: 0.2

phases:
  pre_build:
    commands:
      - echo "Cleaning 'build' folder before build commenses..."
  build:
    commands:
      - echo "Building bundle..."
  post_build:
    commands:
      - echo "Updating S3 buckets with 'build' folder..."