version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies for 'johnmacintire.com' build..."
      - npm install
  pre_build:
    commands:
      - echo "Cleaning 'build' folder and S3 buckets..."
      - npm run clean
      - npm run clean-buckets
  build:
    commands:
      - echo "Bundling production version into 'build'..."
      - npm run build
  post_build:
    commands:
      - echo "Update S3 bucket hosting 'johnmacintire.com'..."
      - npm run sync-bucket

cache:
  paths:
    - '/node_modules/**/*'